#
# This workflow builds a JSON ARM template from Bicep code
#

name: Build-JSON-From-Bicep

on:
  push:
    branches: 
      - main
    paths: 
      - 'Build-AD-Domain-Bicep/**'

  workflow_dispatch:

jobs:
  Convert-To-JSON:
    runs-on: windows-latest
    steps:
      - name: Check out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2

      - name: Bicep-Build
        run: |
          az bicep build --file Build-AD-Domain-Bicep\main.bicep
          dir
      
      - name: Add-JSON-To-GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          message: Add JSON file to GitHub
          add: Build-AD-Domain-Bicep\main.json
