name: Install Bicep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-bicep:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Install Bicep CLI
        run: |
          az bicep install
          az bicep version
