#
# This workflow deploys the Azure management group hierarchy
#

name: Infra-MG-Deploy

on:
  push:
    branches: [ none ]
  workflow_dispatch:
      inputs:
        orgRootMg:
          type: string
          description: 'Organisation root management group'
          required: true
          default: 'OrgRoot'
        mgRegion:
          type: choice
          description: 'Management group region'
          default: 'uksouth'
          options:
            - "uksouth"
            - "ukwest"

jobs:
  deploy-mg:
    runs-on: windows-latest
    steps:
      - name: Check out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2

      - name: Log on to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Deploy Management Groups
        uses: azure/powershell@v1
        with:
          inlineScript: |   
            #
            # Get supplied parameters
            #
            
            Write-Output "Deploying Azure resources"

          azPSVersion: latest 
